// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjWMURI8Fg0-P4LplrLo2z6EXU6NH2loI',
    appId: '1:188509019257:web:11bcaff3269c2a1ccd08a8',
    messagingSenderId: '188509019257',
    projectId: 'productivity-and-management',
    authDomain: 'productivity-and-management.firebaseapp.com',
    storageBucket: 'productivity-and-management.firebasestorage.app',
    measurementId: 'G-5774RQLDEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATry9iuFkzUU_Dvonz1QdCJtM2sx-AZyU',
    appId: '1:188509019257:android:faae7add3569f356cd08a8',
    messagingSenderId: '188509019257',
    projectId: 'productivity-and-management',
    storageBucket: 'productivity-and-management.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6kQhq7Yc460_hdzUe7qhAhj4pgkEQ0Z4',
    appId: '1:188509019257:ios:8ed65d69fec977b6cd08a8',
    messagingSenderId: '188509019257',
    projectId: 'productivity-and-management',
    storageBucket: 'productivity-and-management.firebasestorage.app',
    iosBundleId: 'com.example.productivityAndManagementTools',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6kQhq7Yc460_hdzUe7qhAhj4pgkEQ0Z4',
    appId: '1:188509019257:ios:8ed65d69fec977b6cd08a8',
    messagingSenderId: '188509019257',
    projectId: 'productivity-and-management',
    storageBucket: 'productivity-and-management.firebasestorage.app',
    iosBundleId: 'com.example.productivityAndManagementTools',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjWMURI8Fg0-P4LplrLo2z6EXU6NH2loI',
    appId: '1:188509019257:web:150f73ec8be0188ecd08a8',
    messagingSenderId: '188509019257',
    projectId: 'productivity-and-management',
    authDomain: 'productivity-and-management.firebaseapp.com',
    storageBucket: 'productivity-and-management.firebasestorage.app',
    measurementId: 'G-S1F0PRY6CX',
  );
}
